// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsewfhsnwifwetzkkxdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZXdmaHNud2lmd2V0emtreGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjcyNzYsImV4cCI6MjA2MDU0MzI3Nn0.xjN0N7nyeVgM0_zcjwNeM45JKtkJqmKRQnhfEkccWoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);